package com.awsserverless.apigatelambda.datamodel.restuarant;

import com.awsserverless.apigatelambda.comfiguration.DBConfiguration;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = DBConfiguration.RESTAURANT_TABLE_NAME )
public class Restuarant {
	private String restaurantID;
	private String restaurantName;
	private String restaurantType;
	private String longitude;
	private String latitude;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "ID")
	public String getRestuarantID()
	{
		return restaurantID;
	}
	public void setRestuarantID(String id)
	{
		restaurantID = id;
	}
	
	@DynamoDBAttribute(attributeName = "Name" )
	public String getRestuarantName()
	{
		return this.restaurantName;
	}
	public void setRestuarantName(String name)
	{
		this.restaurantName = name;
	}
	
	@DynamoDBAttribute(attributeName = "Type" )
	public String getRestuarantType()
	{
		return this.restaurantType;
	}
	public void setRestuarantType(String type)
	{
		this.restaurantType = type;
	}
	
	@DynamoDBAttribute(attributeName = "Longitude" )
	public String getLongitude()
	{
		return this.longitude;
	}
	public void setLongitude(String log)
	{
		this.longitude = log;
	}
	
	@DynamoDBAttribute(attributeName = "Latitude" )
	public String getLatitude()
	{
		return this.latitude;
	}
	public void setLatitude(String log)
	{
		this.latitude = log;
	}
}
